"""Core domain models."""

from __future__ import annotations

from datetime import datetime
from decimal import Decimal
from enum import Enum
from typing import Any, Dict, Optional
from uuid import UUID, uuid4

from pydantic import BaseModel, Field


class Side(str, Enum):
    BUY = "BUY"
    SELL = "SELL"


class SignalType(str, Enum):
    BUY = "BUY"
    SELL = "SELL"
    NEUTRAL = "NEUTRAL"


class PositionStatus(str, Enum):
    OPEN = "OPEN"
    CLOSED = "CLOSED"


class StrategyStatus(str, Enum):
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    DEPRECATED = "DEPRECATED"


class Signal(BaseModel):
    """Trading signal generated by a strategy."""

    strategy_name: str
    ticker: str
    signal_type: SignalType
    strength: float = Field(ge=0.0, le=1.0)
    reason: str = ""
    params: Dict[str, Any] = Field(default_factory=dict)
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class Trade(BaseModel):
    """Executed trade record."""

    id: UUID = Field(default_factory=uuid4)
    strategy_name: str
    ticker: str
    side: Side
    price: Decimal
    quantity: Decimal
    total_krw: Decimal
    fee: Decimal
    reason: str = ""
    profit: Optional[Decimal] = None
    profit_pct: Optional[float] = None
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class Position(BaseModel):
    """Open position."""

    id: UUID = Field(default_factory=uuid4)
    strategy_name: str
    ticker: str
    status: PositionStatus = PositionStatus.OPEN
    entry_price: Decimal
    quantity: Decimal
    entry_time: datetime = Field(default_factory=datetime.utcnow)
    exit_price: Optional[Decimal] = None
    exit_time: Optional[datetime] = None
    highest_price: Optional[Decimal] = None
    profit: Optional[Decimal] = None
    profit_pct: Optional[float] = None

    @property
    def cost(self) -> Decimal:
        return self.entry_price * self.quantity


class Portfolio(BaseModel):
    """Portfolio state."""

    krw_balance: Decimal = Decimal("1000000")
    positions: Dict[str, Position] = Field(default_factory=dict)
    total_trades: int = 0
    winning_trades: int = 0
    total_profit: Decimal = Decimal("0")

    @property
    def win_rate(self) -> float:
        if self.total_trades == 0:
            return 0.0
        return self.winning_trades / self.total_trades

    def position_value(self, prices: Dict[str, Decimal]) -> Decimal:
        total = Decimal("0")
        for ticker, pos in self.positions.items():
            if pos.status == PositionStatus.OPEN:
                price = prices.get(ticker, pos.entry_price)
                total += pos.quantity * price
        return total

    def total_value(self, prices: Dict[str, Decimal]) -> Decimal:
        return self.krw_balance + self.position_value(prices)


class MarketSnapshot(BaseModel):
    """Point-in-time market data."""

    ticker: str
    price: Decimal
    open_price: Optional[Decimal] = None
    high_price: Optional[Decimal] = None
    low_price: Optional[Decimal] = None
    volume: Optional[Decimal] = None
    change_pct: Optional[float] = None
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class AIDecision(BaseModel):
    """Record of an AI decision."""

    id: UUID = Field(default_factory=uuid4)
    model: str
    signal_id: Optional[str] = None
    ticker: str
    decision: str  # "EXECUTE" | "SKIP" | "MODIFY"
    reasoning: str
    confidence: float = Field(ge=0.0, le=1.0)
    market_context: Dict[str, Any] = Field(default_factory=dict)
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class StrategyConfig(BaseModel):
    """Persisted strategy configuration."""

    id: UUID = Field(default_factory=uuid4)
    name: str
    template: str
    params: Dict[str, Any]
    status: StrategyStatus = StrategyStatus.ACTIVE
    sharpe_ratio: Optional[float] = None
    win_rate: Optional[float] = None
    return_pct: Optional[float] = None
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
